In [1]:
import cv2
import numpy as np

img = cv2.imread('C://Users//Public//Pictures//Sample Pictures//Penguins.jpg',cv2.IMREAD_COLOR)
px = img[55,55] #Get color at that postion
print(px)
img[55,55] = [255,255,255] #change color that postion
px=img[55,55]
print(px)

[218 182 122]
[255 255 255]


In [2]:
px = img[100:150,100:150]
print(px)
img[100:150,100:150] = [255,255,255]


[[[233 188 150]
  [229 188 143]
  [229 189 141]
  ..., 
  [231 187 140]
  [232 190 143]
  [232 190 145]]

 [[226 188 146]
  [226 188 140]
  [227 185 138]
  ..., 
  [230 188 141]
  [229 188 139]
  [230 190 137]]

 [[228 186 143]
  [229 189 141]
  [225 187 139]
  ..., 
  [228 186 141]
  [226 186 137]
  [227 190 134]]

 ..., 
 [[233 178 147]
  [232 187 150]
  [232 187 150]
  ..., 
  [235 184 144]
  [233 184 146]
  [231 185 144]]

 [[234 181 144]
  [232 187 150]
  [233 188 150]
  ..., 
  [235 190 147]
  [235 189 148]
  [232 186 145]]

 [[232 183 145]
  [233 185 151]
  [231 186 149]
  ..., 
  [235 188 144]
  [236 189 145]
  [232 184 142]]]


In [3]:
print(img.shape)
print(img.size)
print(img.dtype)

(768, 1024, 3)
2359296
uint8


In [4]:
watch_face = img[274:548,107:294]
img[0:274,0:187] = watch_face

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()